### PR TITLE
Add S3Error

### PR DESCRIPTION
**Pull request by matthewmturner**
Rebase

### CODE REVIEW

**Comment by matthewmturner** [comment]
Probably nothing to do here, for now, as the `ObjectStore` and `ObjectReader` traits require `DatafusionError` and `Result`

**Comment by matthewmturner** [comment]
@houqp im interested in your thoughts on this.  should crates such as this have their own errors or should they just reuse datafusion error and result?  To me it would seem there is value in changing the signatures for the `ObjectStore` and `ObjectReader` to allow any type that implements `Error` or `io::Error`.  This way there is clear separation between whats an actual datafusion error or 3rd party error like this.

**Comment by houqp** [comment]
I think changing object store interface upstream to make it more generic makes sense, we probably want to use `std::error::Error` trait instead of `io:Error`. cc @yjshen in case he has any comment on this since he wrote the object store abstraction ;)

**Comment by yjshen** [comment]
+1 to use std::error::Error trait instead of io:Error upstream

**Comment by matthewmturner** [comment]
@houqp @yjshen thank you, both

**Comment by matthewmturner** [comment]
@seddonm1 would you mind checking this out?

**Comment by seddonm1** [comment]
@matthewmturner looks good. I think we should wait for the official release rather than pointing to a commit?

```
{git = "https://github.com/apache/arrow-datafusion", rev = "7b8d72c5342610a40827f23df7d5604cf24133fd"}
```

**Comment by matthewmturner** [comment]
@seddonm1 personally, i wasnt opposed to leaving it like that until the next datafusion release just so we could continue iterating with this included in case it was needed.  but i dont have strong feeling on the matter so happy to wait until next release.

**Comment by seddonm1** [comment]
@matthewmturner I am ok for you to merge this if we don't publish this crate until the datafusion release and the crate updated?

**Comment by matthewmturner** [comment]
@seddonm1 absolutely. definitely would not publish with it pointing to a commit.

**Pull request merged**
