### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by matthewmturner** [comment]
@seddonm1 if i recall, you wanted to update readme.

let me know if you want to make updates yourself or im happy to add for you if you let me know what you want added.

**Comment by seddonm1** [comment]
I wanted to add something about registering the object store against the execution provider. This is how most people should be using this plugin.

```rust 
execution_ctx.register_object_store(
    "s3",
    Arc::new(AmazonS3FileSystem::new(None, None, None, None, None, None).await),
);
```

It can then be retrieved from the context based on the URI scheme like:

```rust
let input_uri = "s3://parquet-testing/data/alltypes_plain.snappy.parquet";

let (object_store, _) = ctx.object_store(input_uri)?;

let resolved_schema = listing_options
    .infer_schema(object_store.clone(), input_uri)
    .await
    .map_err(BoxError::from)?;

let mut table_provider: Arc<dyn TableProvider + Send + Sync> = Arc::new(ListingTable::new(
    object_store,
    input_uri.to_string(),
    resolved_schema,
    listing_options,
));
```

**Comment by matthewmturner** [comment]
This is great. I had wanted to add something on the idiomatic way to use `ctx.register_object_store`.

**Comment by seddonm1** [comment]
of course we should also use the `default()` method in the docs

**Comment by matthewmturner** [comment]
Yes agree, was going to add that once it was merged

**Comment by seddonm1** [comment]
👍

**Comment by matthewmturner** [comment]
@seddonm1 good to merge?

**Comment by seddonm1** [comment]
yes

**Pull request merged**
