### PR TITLE
Added query test and readme example

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by seddonm1** [comment]
Looks good. My only comment would be something to the readme about using non-aws sources and credentials. 👍

**Comment by matthewmturner** [comment]
> Looks good. My only comment would be something to the readme about using non-aws sources and credentials. 👍

yes sure will do.  still have to fix the test i added too.

**Comment by matthewmturner** [comment]
@seddonm1 with that line of thinking - do you think we should generalize and remove references to "Amazon" from `AmazonS3FileSystem` and `AmazonS3FileReader` and the module could be `s3` instead of `aws`?

**Comment by seddonm1** [comment]
@matthewmturner I think Amazon probably 'owns' the standard and majority of people will use Amazon S3.

I hope the readme can just clarify to users they can use with alternatives (minio, ceph, etc)

**Comment by matthewmturner** [comment]
@seddonm1 ok sure sounds good.

**Comment by seddonm1** [comment]
I think this is good to merge. I might make some changes to README once merged just to clarify how the credentials work.

**Comment by matthewmturner** [comment]
just want to fix my test, wanted to use `assert_batches_eq` macro like we do in datafusion. will have that done soon then will merge

**Pull request merged**
